name: chip-downsampling
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-rsubread=1.34.0
  - macs2=2.1.2
  - python=2.7.15
  - r-base=3.5.1
  - r-getopt=1.20.3
  - r-tidyverse=1.2.1
  - samtools=1.9
